### ISSUE TITLE
Pip installer?

### ISSUE THREAD

**Issue by rpanai** [facebookresearch/KILT#16]
Hi All, are you planning to make this pip installable?

**Comment by petulla** [comment]
@rpanai have you tried [pip installing the repo](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)?

**Comment by rpanai** [comment]
> @rpanai have you tried [pip installing the repo](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch)?

Hi @petulla the idea is to make a conda package out of it. If it's on pipy it's easier to make a recipe that update automatically.

**Comment by fabiopetroni** [comment]
Hi @rpanai, we plan to put KILT on pypi sooner or later (not a priority at the moment). As @petulla mentioned, you can install the repo with pip also in the current setup.
