### ISSUE TITLE
Error connecting to db server

### ISSUE THREAD

**Issue by wojdygagrzegorz** [facebookresearch/KILT#18]
Hi, 

after running 
`mongoimport --db kilt --collection knowledgesource --file kilt_knowledgesource.json`

I constantly receive

`2020-10-07T13:54:09.824+0200	[........................] kilt.knowledgesource	0B/34.8GB (0.0%)`
`2020-10-07T13:54:10.331+0200	[........................] kilt.knowledgesource	0B/34.8GB (0.0%)`
`2020-10-07T13:54:10.331+0200	Failed: error connecting to db server: no reachable servers`
`2020-10-07T13:54:10.331+0200	imported 0 documents`

I everything OK with the server?

**Comment by fabiopetroni** [comment]
Hey @wojdygagrzegorz, we don't host any server. You should handle the knowledge_source on your side
