### ISSUE TITLE
Integration with DPR Repository

### ISSUE THREAD

**Issue by anthonywchen** [facebookresearch/KILT#22]
Hello! Thank you for the great repository/paper. I noticed some issues with how some of the [DPR_connector code](https://github.com/facebookresearch/KILT/blob/master/kilt/retrievers/DPR_connector.py) interacts with the [DPR](https://github.com/facebookresearch/DPR/) repository.

1. This [line](https://github.com/facebookresearch/KILT/blob/2130aafaaee0671bdbd03d781b1fa57ee02650d2/kilt/retrievers/DPR_connector.py#L86) leads to an error because `DenseRetriever` class in the DPR repo doesn't have that function. I believe that this line should be changed to: `self.retriever.index.index_data(input_paths)`

2. This is really minor: In the [Retriever README](https://github.com/facebookresearch/KILT/tree/2130aafaaee0671bdbd03d781b1fa57ee02650d2/kilt/retrievers) there is this instruction: 

> change line 185 of src/dpr/dense_retriever.py to
>```
> try:
>     db_id, doc_vector = doc
> except:
>     title, db_id, doc_vector = doc
> ```
except that this isn't line 185 anymore. 

Thanks again for the great work!

Best,
Anthony

**Comment by fabiopetroni** [comment]
Hey @anthonywchen, if you can include also this fix in your pull request would be great! :)

**Comment by anthonywchen** [comment]
Sure :)

**Comment by yuwfan** [comment]
Thanks @anthonywchen and @anthonywchen. I opened a PR for this issue: https://github.com/facebookresearch/KILT/pull/29.

**Comment by anthonywchen** [comment]
I noticed that making this change isn't necessary to get DPR to work: 
`try:
    db_id, doc_vector = doc
except:
    title, db_id, doc_vector = doc`
I can remove this from the retriever README when making the pull request for the other issue

**Comment by fabiopetroni** [comment]
THANKS A LOT ! :)
