### ISSUE TITLE
Aligning new datasets into KILT format

### ISSUE THREAD

**Issue by eisenjulian** [facebookresearch/KILT#24]
Congrats on the great work. I was thinking on aligning a new dataset into the KILT format to facilitate adoption, can you comment if:
1. You would consider additions to the benchmark if it fits the task spirit.
2. The code that does the transform and alignment (for example for Fever or NQ) will be released, after a quick search I couldn't find it.

Thanks!

**Comment by fabiopetroni** [comment]
Hey @eisenjulian,

Thanks for your message and kind words.

1. Definitely! We plan to continue collecting dataset to the pull!

2. Does your dataset use a different Wikipedia dump? If yes, I can try to release a minimal script for the alignment

Thanks,
Fabio

**Comment by eisenjulian** [comment]
Hi @fabiopetroni,
Thanks for the quick response. Regarding 2. indeed it has a different Wikipedia version, so having the standard logic used for the alignment would be super useful, and hopefully other people can use it as well to add more datasets.

Best,
Julian

**Comment by fabiopetroni** [comment]
Hey @eisenjulian .

we just added an example script to map a dataset to KILT format - see https://github.com/facebookresearch/KILT/blob/master/scripts/map_datasets.py

:)
