### ISSUE TITLE
Tac-kbp 2010 dataset format

### ISSUE THREAD

**Issue by WenzhengZhang** [facebookresearch/KILT#28]
Hi, could you tell me what's the format of tackbp 2010 dataset you used for this [script](https://github.com/facebookresearch/KILT/blob/master/scripts/map_TAC-KBP2010_to_KILT.py)? I remeber the raw tackbp dataset I got is xml file. Do I need to process the raw tackbp 2010 dataset so that I can use your script? Thanks!

**Comment by ManyaWadhwa** [comment]
Following this issue! Can you please provide the conversion script for the tackbp 2010 dataset to the train.jsonl/test.jsonl you have mentioned in the code? Thankyou!
