### ISSUE TITLE
eli5 implicit knowledge model reproduce scores 

### ISSUE THREAD

**Issue by dptam** [facebookresearch/KILT#33]
Hi, I saw the scores for t5-base and bart models using implicit knowledge get around 19-20 rougeL, and was having issues matching that score. Currently, I am getting around 11 rougeL. I was wondering what hyperparameters and scheduler were used? Thanks

**Comment by fabiopetroni** [comment]
Hey @dptam, I've just pushed some script to reproduce t5 results. :)
