### ISSUE TITLE
Licensing information for KILT-TriviaQA

### ISSUE THREAD

**Issue by akhilkedia** [facebookresearch/KILT#53]
Does KILT provide any licensing for the use of TriviaQA dataset included in KILT? 

The original TriviaQA website at http://nlp.cs.washington.edu/triviaqa/ mentions they do not own the copyright of the questions included in the dataset.

**Comment by fabiopetroni** [comment]
Correct, we don't own the copyright - therefore we are not releasing the questions. You need to execute a script to retrieve those from the original TriviaQA website.
